tcpdrop: Fix: ERROR: Error attaching probe: 'kprobe:tcp_drop'
iovisor/bpftrace pull request #2379
Opened 2022-10-01 08:17 UTC by Rtoax

kernel commit 8fbf195798b5('tcp_drop() is no longer needed.') remove the kprobe:tcp_drop, bcc commit 16eab39171eb('Add
tracepoint:skb:kfree_skb if no tcp_drop() kprobe.') already fix this problem.

ERROR log:
```bash
 $ sudo ./tcpdrop.bt
 ./tcpdrop.bt:49-51: WARNING: tcp_drop is not traceable (either non-existing, inlined, or marked as "notrace"); attaching to it will likely fail
 Attaching 3 probes...
 cannot attach kprobe, probe entry may not exist
 ERROR: Error attaching probe: 'kprobe:tcp_drop'
```

2022-10-04 05:48 UTC, viktormalik commented
The tool is crashing in the CI, can you debug it?

2022-10-06 14:05 UTC, Rtoax commented
> The tool is crashing in the CI, can you debug it?

OK, i'll try to fix that.

2022-10-07 06:24 UTC, viktormalik commented
> Hi, @viktormalik , My env is kernel 5.15 on centos-stream9, CI env has a wrong kernel version? should i fix CI kernel version, and how to modify it?

Hi, unfortunately, we cannot control the CI kernel (yet). The likely problem here is that the kernel is too old and the `reason` field, as well as the corresponding enum, don't exist. The preferred way is to make the tool as generic as possible, but if that's not an option, we can have multiple implementations of the tool - just move the old one into `tools/old` and set the CI to use it (see e.g. `biosnoop.bt`).

2022-10-07 06:50 UTC, Rtoax commented
Is this done right?

2022-10-19 05:40 UTC, viktormalik commented
> @viktormalik Hi, Is this done right?

Yes, but the comments in the tools headers need to be adjusted. Please add a specific kernel version from which the new version is necessary.

2022-10-20 14:22 UTC, Rtoax commented
@viktormalik Hi, i specific kernel version in comment.

Useful hint:

```
Since 5.17 support trace_kfree_skb(skb, ..., reason) 'reason' field.
Since 5.19 remove tcp_drop() function.
```

2022-10-21 06:11 UTC, viktormalik requested changes

2022-10-21 06:11 UTC, viktormalik commented on tools/tcpdrop.bt
>   *          the script will stop working
This should go away in the new version of the script.

2022-10-21 06:11 UTC, viktormalik commented on tools/tcpdrop.bt
>   * stack trace for packets/segments that were dropped via tcp_drop().
`tcp_drop()` is not called in the new version so the description should be updated.

2022-10-21 06:51 UTC, viktormalik approved these changes

2022-11-03 06:52 UTC, merged