Rawtracepoint support wildcards and list show
iovisor/bpftrace pull request #2588
Opened 2023-05-05 07:33 UTC by zf1575192187

1: Rawtracepoint support wildcards and list show
2: Add testcases for rawtracepoint's wildcards and list show

2023-05-11 11:01 UTC, viktormalik reviewed
A runtime test for an actual attachment to a wildcarded raw tracepoint would be useful.

Other than that looks good to me, thanks!

2023-05-12 07:18 UTC, zf1575192187 commented on src/probe_matcher.cpp
> +    }
Done, thanks

2023-05-12 07:18 UTC, zf1575192187 commented on src/ast/attachpoint_parser.cpp
> +  if (ap_->func.find('*') != std::string::npos)
Done, thanks

2023-05-15 05:34 UTC, viktormalik approved these changes

2023-05-15 07:56 UTC, viktormalik requested changes
I just realized that this is not properly handling `argX` for wildcarded probes.
Example:
```
# bpftrace -e 'rawtracepoint:mm_* { printf("%d\n", arg1); exit(); }'
Attaching 50 probes...
ERROR: Error attaching probe: rawtracepoint:mm_compaction_kcompactd_sleep
```
`mm_compaction_kcompactd_sleep` has only one argument so the verifier rejects to attach the above program to it. We should address this in semantic analyzer and provide a reasonable error message.

2023-05-16 03:45 UTC, zf1575192187 commented
Ok, thanks for helping with the test, I'll check it out.

2023-05-19 10:18 UTC, viktormalik commented
> Considering that it is difficult to obtain the number of parameters of rawtracepoint, whether it can be handled simply, and prompt after judging the error
> 
> ```
> else if (tracing_fd_ == -EINVAL)
>       throw std::runtime_error("Error attaching probe: " + probe_.name + ", \
>         Maybe access arguments beyond what's available in this tracepoint");
> ```
> 
> @viktormalik What do you think, or is there a better way

Right, I didn't realize that. Checking the error code and printing a hint seems like a reasonable approach to me.

2023-05-22 07:50 UTC, viktormalik approved these changes
One more nit below, otherwise lgtm, thanks! Also, I'm gonna squash the commits on merging, if you don't mind.

2023-05-22 07:50 UTC, viktormalik commented on src/attached_probe.cpp
> +                               ", maybe access arguments beyond what's "
```suggestion
                               ", maybe trying to access arguments beyond what's "
```

2023-05-23 03:51 UTC, zf1575192187 commented on src/attached_probe.cpp
> +                               ", maybe access arguments beyond what's "
It's ok, thanks.
Done.

2023-05-23 06:53 UTC, viktormalik commented
Ah, we'll need a CHANGELOG update, too. Thanks!

2023-05-24 06:18 UTC, zf1575192187 commented
Done

2023-05-24 06:53 UTC, merged